/// Product dimension: catalog with category hierarchy, list price and cost.
table DimProducts

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: "R$" #,0.00
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = User

	column unit_cost
		dataType: double
		formatString: "R$" #,0.00
		summarizeBy: none
		sourceColumn: unit_cost

		annotation SummarizationSetBy = User

	hierarchy 'Product Hierarchy'

		level Category
			column: category

		level Subcategory
			column: subcategory

		level Product
			column: product_name

	partition DimProducts = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolderPath & "\dim_products.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedType = Table.TransformColumnTypes(
						PromotedHeaders,
						{
							{"product_id", type text},
							{"product_name", type text},
							{"category", type text},
							{"subcategory", type text},
							{"unit_price", type number},
							{"unit_cost", type number}
						},
						"en-US"
					)
				in
					ChangedType

	annotation PBI_ResultType = Table
