/// Sales fact table: one row per order line, imported from fact_sales.csv.
table FactSales

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: "R$" #,0.00
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = User

	column discount_pct
		dataType: double
		formatString: 0%;-0%;0%
		summarizeBy: none
		sourceColumn: discount_pct

		annotation SummarizationSetBy = User

	partition FactSales = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolderPath & "\fact_sales.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedType = Table.TransformColumnTypes(
						PromotedHeaders,
						{
							{"order_id", type text},
							{"order_date", type date},
							{"customer_id", type text},
							{"product_id", type text},
							{"quantity", Int64.Type},
							{"unit_price", type number},
							{"discount_pct", type number}
						},
						"en-US"
					)
				in
					ChangedType

	annotation PBI_ResultType = Table
